Models/Computer.cs
namespace MvcLabManager.Models;

public class Computer
{
    public int? Id { get; set; }
    public string? Ram { get; set; }
    public string? Processor { get; set; }

    public Computer() 
    {

    }

    public Computer(int id, string ram, string processor)
    {
        Id = id;
        Ram = ram;
        Processor = processor;
    }
}

Models/ErrorViewModel.cs
namespace MvcLabManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Lab.cs
namespace MvcLabManager.Models;

public class Lab
{
    public int? Id { get; set; }
    public int? Number { get; set; }
    public string? Name { get; set; }
    public string? Block { get; set; }

    public Lab() 
    {
        
    }

    public Lab(int id, int number, string name, string block)
    {
        Id = id;
        Number = number;
        Name = name;
        Block = block;
    }
}

Models/LabManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MvcLabManager.Models;

public class LabManagerContext : DbContext
{
    public DbSet<Computer>? Computers { get; set; }
    public DbSet<Lab>? Labs { get; set; }
    
    public LabManagerContext(DbContextOptions<LabManagerContext> options) : base(options)
    {
        
    }
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class ComputerController : Controller
{
    private readonly LabManagerContext _context;

    public ComputerController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index() {
        return View(_context.Computers);
    } 

    public IActionResult Show(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound(); // RedirectToAction("Index")
        }

        return View(computer);
    }

    public IActionResult Cadastrar(int id, string ram, string processor)
    {
        return View();
    }

    public IActionResult CadastrarComputador(Computer computer)
    {
        _context.Computers.Add(computer);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    public IActionResult Deletar(int id)
    {
        Computer computer = _context.Computers.Find(id);
        if(computer == null)
        {
            return NotFound();
        }

        _context.Computers.Remove(_context.Computers.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    public IActionResult Atualizar(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }

    [HttpPost]
    public IActionResult Atualizar(Computer computer)
    {
        Computer computadorAtualizado = _context.Computers.Find(computer.Id);

        if(computadorAtualizado == null)
        {
            return NotFound();
        }

        computadorAtualizado.Processor = computer.Processor;
        computadorAtualizado.Ram = computer.Ram;

        _context.Computers.Update(computadorAtualizado);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LabController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class LabController : Controller
{
    private readonly LabManagerContext _context;

    public LabController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index() {
        return View(_context.Labs);
    } 

    public IActionResult Show(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    [HttpGet]
    public IActionResult Cadastrar(int id, string ram, string processor)
    {
        return View();
    }

    [HttpPost]
    public IActionResult Cadastrar(Lab lab)
    {
        _context.Labs.Add(lab);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Atualizar(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    [HttpPost]
    public IActionResult Atualizar(Lab lab)
    {
        Lab labAtualizado = _context.Labs.Find(lab.Id);

        if(labAtualizado == null)
        {
            return NotFound();
        }

        labAtualizado.Number = lab.Number;
        labAtualizado.Name = lab.Name;
        labAtualizado.Block = lab.Block;

        _context.Labs.Update(labAtualizado);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    public IActionResult Deletar(int id)
    {
        Lab lab = _context.Labs.Find(id);
        if(lab == null)
        {
            return NotFound();
        }

        _context.Labs.Remove(_context.Labs.Find(id));
        _context.SaveChanges();

        return RedirectToAction("Index");
    }
}

Views/Computer/Atualizar.cshtml
@model MvcLabManager.Models.Computer

    @{
        ViewData["Title"] = "Atualizar";
    }

<h1>@ViewData["Title"]</h1>

<h1>Atualize as informações do computador</h1>

<form method="POST" asp-controller="Computer" asp-action="Atualizar">

    <label for="Ram">Ram: </label>
    <input type="text" id="Ram" value="@Model.Ram" name="Ram">

    <label for="Processor">Processador: </label>
    <input type="text" id="Processor" value="@Model.Processor" name="Processor">

    <input type="submit" value="Atualizar">

</form>

Views/Computer/Cadastrar.cshtml
@model IEnumerable<MvcLabManager.Models.Computer>

    @{
        ViewData["Title"] = "Cadastrar";
    }

<h1>@ViewData["Title"]</h1>

<h1>Cadastre um computador</h1>

<form class="form" asp-controller="Computer" asp-action="CadastrarComputador" method="POST">

    <label for="id">Id: </label>
    <input type="text" id="id" name="id">

    <label for="Ram">Ram: </label>
    <input type="text" id="Ram" name="Ram">

    <label for="Processor">Processador: </label>
    <input type="text" id="Processor" name="Processor">

    <input type="submit" value="Adicionar">

</form>

Views/Computer/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Computer>

@{
    ViewData["Title"] = "Computadores";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum computador cadastrado!</p>
    <a class="btn btn-primary btn-sm" asp-action="Cadastrar">Cadastre um novo computador</a>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ram</th>
                <th>Processor</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var computer in Model){
                <tr>
                    <td>@computer.Id</td>
                    <td>@computer.Ram</td>
                    <td>@computer.Processor</td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-controller="Computer" asp-action="Show" asp-route-id="@computer.Id">Ver</a>
                        <a class="btn btn-primary btn-sm" asp-controller="Computer" asp-action="Atualizar" asp-route-id="@computer.Id">Atualizar</a>
                        <a class="btn btn-primary btn-sm" asp-controller="Computer" asp-action="Deletar" asp-route-id="@computer.Id">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary btn-sm" asp-action="Cadastrar">Cadastre um novo computador</a>
}

Views/Computer/Show.cshtml
@model MvcLabManager.Models.Computer

    @{
        ViewData["Title"] = $"Computador {Model.Id}";
    }
<h1>@ViewData["Title"]</h1>

<p><b>Id </b>@Model.Id</p>
<p><b>Ram: </b>@Model.Ram</p>
<p><b>Processor: </b>@Model.Processor</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lab/Atualizar.cshtml
@model MvcLabManager.Models.Lab

    @{
        ViewData["Title"] = "Atualizar";
    }

<h1>@ViewData["Title"]</h1>

<h1>Atualize as informações do laboratório</h1>

<form method="POST" asp-controller="Lab" asp-action="Atualizar">

    <label for="Number">Number: </label>
    <input type="text" id="Number" name="Number">

    <label for="Name">Name: </label>
    <input type="text" id="Name" name="Name">

    <label for="Block">Block: </label>
    <input type="text" id="Block" name="Block">

    <input type="submit" value="Atualizar">

</form>

Views/Lab/Cadastrar.cshtml
@model IEnumerable<MvcLabManager.Models.Lab>

    @{
        ViewData["Title"] = "Cadastrar";
    }

<h1>@ViewData["Title"]</h1>

<h1>Cadastre um laboratório</h1>

<form method="POST" asp-controller="Lab" asp-action="Cadastrar">

    <label for="Number">Number: </label>
    <input type="text" id="Number" name="Number">

    <label for="Name">Name: </label>
    <input type="text" id="Name" name="Name">

    <label for="Block">Block: </label>
    <input type="text" id="Block" name="Block">

    <input type="submit" value="Cadastrar">

</form>

Views/Lab/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Lab>

@{
    ViewData["Title"] = "Laboratórios";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum laboratório cadastrado!</p>
    <a class="btn btn-primary btn-sm" asp-action="Cadastrar">Cadastre um novo laboratório</a>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Number</th>
                <th>Name</th>
                <th>Block</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var lab in Model){
                <tr>
                    <td>@lab.Id</td>
                    <td>@lab.Number</td>
                    <td>@lab.Name</td>
                    <td>@lab.Block</td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-controller="Lab" asp-action="Show" asp-route-id="@lab.Id">Ver</a>
                        <a class="btn btn-primary btn-sm" asp-controller="Lab" asp-action="Atualizar" asp-route-id="@lab.Id">Atualizar</a>
                        <a class="btn btn-primary btn-sm" asp-controller="Lab" asp-action="Deletar" asp-route-id="@lab.Id">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary btn-sm" asp-action="Cadastrar">Cadastre um novo laboratório</a>
}

Views/Lab/Show.cshtml
@model MvcLabManager.Models.Lab

    @{
        ViewData["Title"] = $"Laboratório {Model.Id}";
    }
<h1>@ViewData["Title"]</h1>

<p><b>Id </b>@Model.Id</p>
<p><b>Number: </b>@Model.Number</p>
<p><b>Name: </b>@Model.Name</p>
<p><b>Block: </b>@Model.Block</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLabManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLabManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLabManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Index">Computers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lab" asp-action="Index">Labs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLabManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>